[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
build-mode = "module"
version = "19.09.37"
included-patches = "'Video ads' 'Hide ads' 'Minimized playback' 'Remove tracking query parameter' 'Bypass URL redirects' 'Open links externally' 'Disable zoom haptics' 'Remember video quality' 'Enable slide to seek' 'Disable precise seeking gesture' 'Seekbar tapping' 'Remove viewer discretion dialog' 'Disable player popup panels' 'Hide cast button' 'Navigation buttons' 'Disable resuming Shorts on startup' 'Hide breaking news shelf' 'Hide Shorts components' 'Disable rolling number animations' 'Hide floating microphone button' 'Hide endscreen cards' 'Hide crowdfunding box' 'Disable suggested video end screen' 'Hide 'Load more' button' 'Hide album cards' 'Hide filter bar' 'Hide layout components' 'Hide info cards'"
exclusive-patches = true

