[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
version = "auto"
excluded-patches = "custom-branding disable-fullscreen-panels enable-debugging external-downloads old-quality-layout premium-heading remember-video-quality return-youtube-dislike spoof-app-version swipe-controls tablet-mini-player theme video-speed wide-searchbar"

