[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
arch = "arm64-v8a"
version = "auto"
excluded-patches = "disable-fullscreen-panels external-downloads premium-heading return-youtube-dislike spoof-app-version swipe-controls tablet-mini-player theme video-speed wide-searchbar"

