[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
version = "18.20.39"
included-patches = "remove-player-controls-background"
excluded-patches = "always-autorepeat comments copy-video-url custom-branding disable-auto-captions disable-fullscreen-panels enable-debugging external-downloads hdr-auto-brightness hide-player-buttons hide-player-overlay hide-seekbar hide-timestamp hide-video-action-buttons playback-speed premium-heading return-youtube-dislike seekbar-tapping spoof-app-version swipe-controls tablet-mini-player theme wide-searchbar"

