[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
version = "18.20.39"
excluded-patches = "always-autorepeat comments copy-video-url custom-branding disable-auto-captions disable-fullscreen-panels enable-debugging external-downloads hide-autoplay-button hide-captions-button hide-player-buttons hide-player-overlay hide-timestamp hide-video-action-buttons premium-heading return-youtube-dislike seekbar-tapping spoof-app-version swipe-controls tablet-mini-player theme wide-searchbar"

