[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
build-mode = "module"
version = "18.20.39"
included-patches = "'Disable Shorts on startup' 'Disable auto captions' 'Disable fullscreen panels' 'Disable player popup panels' 'Disable zoom haptics' 'Hide Shorts components' 'Hide ads' 'Hide album cards' 'Hide autoplay button' 'Hide breaking news shelf' 'Hide cast button' 'Hide crowdfunding box' 'Hide email address' 'Hide endscreen cards' 'Hide filter bar' 'Hide floating microphone button' 'Hide info cards' 'Hide layout components' 'Hide load more button' 'Hide seekbar' 'Hide watermark' 'Minimized playback' 'Navigation buttons' 'Open links externally' 'Remember video quality' 'Video ads'"
exclusive-patches = true

