[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
patches-source = "ReVanced/revanced-patches-2.187.0.jar"
integrations-source = "ReVanced/revanced-integrations"
rv-brand = "ReVanced ReVanced"
build-mode = "module"
version = "18.20.39"
included-patches = "'Disable player popup panels' 'Disable resuming Shorts on startup' 'Hide autoplay button' 'Hide captions button' 'Navigation buttons' 'Hide cast button' 'Disable auto captions' 'Hide info cards' 'Hide floating microphone button' 'Hide album cards' 'Hide crowdfunding box' 'Hide breaking news shelf' 'Hide endscreen cards' 'Hide layout components' 'Hide Shorts components' 'Hide filter bar' 'Hide 'Load more' button' 'Disable suggested video end screen' 'Remember video quality' 'Video ads' 'Hide ads' 'Minimized playback' 'Open links externally' 'Bypass URL redirects' 'Disable zoom haptics'"
exclusive-patches = true

