[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
apkmirror-arch = "arm64-v8a"
version = "18.19.35"
included-patches = "client-spoof disable-shorts-on-startup disable-player-popup-panels disable-zoom-haptics hide-shorts-components hide-ads hide-album-cards hide-breaking-news-shelf hide-cast-button hide-crowdfunding-box hide-email-address hide-endscreen-cards hide-filter-bar hide-floating-microphone-button hide-info-cards hide-layout-components hide-load-more-button hide-watch-in-vr hide-watermark minimized-playback navigation-buttons open-links-externally remember-video-quality sponsorblock vanced-microg-support video-ads"
exclusive-patches = true
