[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
build-mode = "both"
version = "19.16.39"
included-patches = "'Disable player popup panels' 'Hide album cards' 'Disable rolling number animations' 'Disable suggested video end screen' 'Hide crowdfunding box' 'Disable fullscreen ambient mode' 'Hide endscreen cards' 'Hide Shorts components' 'Hide floating microphone button' 'Hide info cards' 'Hide filter bar' 'Hide layout components' 'Disable resuming Shorts on startup' 'Restore old seekbar thumbnails' 'Hide cast button' 'Navigation buttons' 'Bypass image region restrictions' 'GmsCore support' 'Disable zoom haptics' 'Open links externally' 'Bypass URL redirects' 'Remove tracking query parameter' 'Remove background playback restrictions' 'Video ads' 'Hide ads' 'Remember video quality' 'Enable slide to seek' 'Seekbar tapping' 'Disable precise seeking gesture' 'Remove viewer discretion dialog'"
exclusive-patches = true

